/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.SistemaAlmacen.General.Utiles;

import java.awt.Image;
import javax.swing.ImageIcon;



public class ModalListo extends javax.swing.JDialog {
    int  xMouse;
    int  yMouse;
    
    public ModalListo(java.awt.Frame parent, boolean modal, String mensajes) {
        super(parent, modal);
        initComponents();
        
        
        pnlDialogListo.setSize(293, 247);
        lbModalListo.setSize(120, 110);
        ImageIcon lol4=new ImageIcon(getClass().getResource("../../imagen/modal_listo.png"));
        ImageIcon img=new ImageIcon(lol4.getImage().getScaledInstance(lbModalListo.getWidth(), lbModalListo.getHeight(), Image.SCALE_DEFAULT));
        lbModalListo.setIcon(img);
        
        lbMensaje.setText(mensajes);
        
        setLocationRelativeTo(null);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDialogListo = new javax.swing.JPanel();
        lbModalListo = new javax.swing.JLabel();
        lbMensaje = new javax.swing.JLabel();
        btnModalConfirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        pnlDialogListo.setBackground(new java.awt.Color(255, 255, 255));
        pnlDialogListo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlDialogListo.setMinimumSize(new java.awt.Dimension(293, 247));
        pnlDialogListo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbModalListo.setMaximumSize(new java.awt.Dimension(400, 400));
        lbModalListo.setMinimumSize(new java.awt.Dimension(120, 110));
        pnlDialogListo.add(lbModalListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, 110));

        lbMensaje.setBackground(new java.awt.Color(255, 255, 255));
        lbMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMensaje.setForeground(new java.awt.Color(102, 102, 102));
        lbMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMensaje.setText("REGISTRO GUARDADO");
        pnlDialogListo.add(lbMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 241, 31));

        btnModalConfirmar.setBackground(new java.awt.Color(0, 204, 51));
        btnModalConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModalConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnModalConfirmar.setText("ACEPTAR");
        btnModalConfirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnModalConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModalConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalConfirmarActionPerformed(evt);
            }
        });
        pnlDialogListo.add(btnModalConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, 250, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlDialogListo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 286, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDialogListo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDialogListo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModalConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalConfirmarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnModalConfirmarActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalListo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalListo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalListo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalListo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnModalConfirmar;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lbMensaje;
    public static javax.swing.JLabel lbModalListo;
    public static javax.swing.JPanel pnlDialogListo;
    // End of variables declaration//GEN-END:variables
}
